spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: wq15156223059
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    root: warn
    com.csust: info
  file:
    path: log/blog-pro.log

server:
  port: 80
  servlet:
    context-path: /blog
